FROM harbor.adamkoro.com/bci/bci-base:15.5

RUN zypper addrepo https://download.opensuse.org/repositories/systemsmanagement:/ansible/openSUSE_Tumbleweed/ && zypper --gpg-auto-import-keys refresh
RUN zypper -n install ansible