kind: pipeline
name: build-harbor
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: generate_password
    image: registry.suse.com/bci/bci-base:15.5
    commands:
      - echo "TF_VAR_linode_root_pass=$(openssl rand -base64 32 | tr -d '\n' | base64 -w 0)" > /build_env/linode_root_pass
    volumes:
      - name: build_env
        path: /build_env

  - name: create_linode
    image: registry.adamkoro.com/docker/hashicorp/terraform:1.5.5
    environment:
      TF_VAR_linode_token:
        from_secret: linode_token
      TF_VAR_linode_authorized_keys:
        from_secret: linode_authorized_keys
    commands:
      - export $(cat /build_env/linode_root_pass | xargs)
      - terraform -chdir=terraform/ init 
      - terraform -chdir=terraform/ plan
      - terraform -chdir=terraform/ apply -auto-approve
    volumes:
      - name: build_env
        path: /build_env
    when:
      status:
        - success

  - name: run_playbook
    image: registry.adamkoro.com/library/ansible-helper:latest
    environment:
      ANSIBLE_USER: root
    commands:
      - export $(cat /build_env/linode_root_pass | xargs)
      - export $(cat /build_env/linode_ip_address | xargs)
      - export ANSIBLE_HOSTS=$(echo $TF_VAR_linode_ip)
      - export ANSIBLE_USER=root
      - export ANSIBLE_PASSWORD=$(echo $TF_VAR_linode_root_pass)
      - export ANSIBLE_HOST_KEY_CHECKING=False
      - ansible-galaxy collection install community.docker
      - ansible-playbook ansible/setup.yml -i "'"${ANSIBLE_HOSTS},"'" -e "ansible_user=${ANSIBLE_USER} ansible_password=${ANSIBLE_PASSWORD} ansible_host_key_checking=${ANSIBLE_HOST_KEY_CHECKING}"
    volumes:
      - name: build_env
        path: /build_env
    when:
      status:
        - success

  - name: delete_linode
    image: registry.adamkoro.com/docker/hashicorp/terraform:1.5.5
    environment:
      TF_VAR_linode_token:
        from_secret: linode_token
      TF_VAR_linode_authorized_keys:
        from_secret: linode_authorized_keys
    commands:
      - export $(cat /build_env/linode_root_pass | xargs)
      - terraform -chdir=terraform/ init 
      - terraform -chdir=terraform/ destroy -auto-approve
    volumes:
      - name: build_env
        path: /build_env
    when:
      status:
        - failure
        - success

volumes:
  - name: build_env
    temp: {}

node:
  type: hosted-amd64
#---
#kind: pipeline
#name: build-ansible-helper
#type: docker
#
#platform:
#  os: linux
#  arch: amd64
#
#steps:
#  - name: build_helper
#    image: gcr.io/kaniko-project/executor:v1.12.0-debug
#    environment:
#      HARBOR_USERNAME:
#        from_secret: registry_user
#      HARBOR_PASSWORD:
#        from_secret: registry_password
#    commands:
#      -  echo "{\"auths\":{\"registry.adamkoro.com\":{\"auth\":\"$(printf "%s:%s" "$HARBOR_USERNAME" "$HARBOR_PASSWORD" | base64 )\"}}}" > /kaniko/.docker/config.json
#      - /kaniko/executor
#        --context "."
#        --dockerfile "./helper/Dockerfile.ansible-helper"
#        --destination "registry.adamkoro.com/library/ansible-helper:latest"
#
#node:
#  type: hosted-amd64